services:
 maestro:
  entrypoint: /home/cosim/entrypoint.sh
  image: prasadtalasila/maestro11-service-openjdk13
  volumes:
   - ./input:/home/input:rw
   - ./model:/home/model:rw
   - ./output:/home/output:rw
  environment:
    MODEL_URL: "https://github.com/prasadtalasila/digitbrain-example/blob/main/example5/model/cosim-model.zip"
version: '3.9'
